# version: "3.1"

# services:
#   db:
#     image: mariadb
#     restart: always
#     environment:
#       MARIADB_ROOT_PASSWORD: example
#       MARIADB_DATABASE: company
#     ports:
#       - 3306:3306

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

version: "3.8"
services:
  # DATENBANK
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  # WEBÖBERFLÄSCHÖ
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # demo:
  #   container_name: localhost
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: test_db
  #   ports:
  #     - "3001:3001"
