services:
  # SERVER
  server:
    image: skyface753/chest-system-server:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 127.0.0.1:8000:8000

  # CLIENT
  client:
    image: skyface753/chest-system-client:latest
    build:
      context: ./react-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 127.0.0.1:3000:3000

  proxy:
    image: skyface753/chest-system-proxy:latest
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 81:80
    restart: always
    depends_on:
      - server
      - client

  # DATENBANK
  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    ports:
      - 8080:8080
    volumes:
      - ./pgbackups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
