version: '3.8'

x-common-variables: &DB_VARIABLES
  DATABASE_HOST: db-dev
  DATABASE_PORT: 5432
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: mysecretpassword
  DATABASE_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: postgres

services:
  # SERVER
  server:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: server_container
    restart: always
    environment:
      <<: *DB_VARIABLES
    ports:
      - '8000:8000'
    volumes:
      - ./app:/web/app
    depends_on:
      db-dev:
        condition: service_healthy

  # DATENBANK
  db-dev:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      <<: *DB_VARIABLES
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 5s
      timeout: 5s
      retries: 5

  # WEBÖBERFLÄSCHÖ
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
