services:
  # SERVER
  server:
    image: skyface753/chest-system-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000

  # CLIENT
  client:
    image: skyface753/chest-system-client:latest
    build:
      context: ./my-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  proxy:
    image: skyface753/chest-system-proxy:latest
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 81:80
    restart: always
    depends_on:
      - server
      - client

  # DATENBANK
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
