"""Added Audit Log

Revision ID: 0fea39c68e95
Revises: babff3249ab1
Create Date: 2024-07-04 05:20:54.396469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fea39c68e95'
down_revision: Union[str, None] = 'babff3249ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditlog')
    # ### end Alembic commands ###
