"""Add chest location

Revision ID: 33f66bc4dced
Revises: 4823ac874e02
Create Date: 2024-03-13 09:02:08.825809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f66bc4dced'
down_revision: Union[str, None] = '4823ac874e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kiste', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kiste', 'location')
    # ### end Alembic commands ###
