apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o kube --namespace chest-system
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
  namespace: chest-system
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 80
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
