apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o kube
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o kube
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chest-system-default: "true"
        io.kompose.service: proxy
    spec:
      containers:
        - image: skyface753/chest-system-proxy:latest
          name: proxy
          ports:
            - containerPort: 80
              hostPort: 81
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
