apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: proxy
  name: chest-proxy-service
  namespace: chest-system
spec:
  ports:
    - name: 'web'
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
---
# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chest-proxy-ingress
  namespace: chest-system
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`chest.it-lab.cc`)
      middlewares:
        - name: redirectscheme
          namespace: default
      services:
        - name: chest-proxy-service
          port: 80
