apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o kube
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-resolved.yaml -o kube
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/chest-system-default: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres3
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PASSWORD
              value: postgres2
            - name: POSTGRES_USER
              value: postgres1
          image: skyface753/chest-system-server:latest
          name: server
          resources: {}
      restartPolicy: Always
status: {}
