name: chest_system_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flex_color_scheme: ^7.3.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  go_router: ^13.1.0
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  # riverpod generator/dev stuff
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.5.11
  very_good_analysis: ^5.1.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  # Localizations Generation
  generate: true
